### ISSUE TITLE
Any chance of allowing bundle creation as tar-gzip via an option switch?

### ISSUE THREAD

**Issue by zappan** [techpivot/aws-code-deploy#11]
Hi,

I'd like to ask is there any chance of enabling the option of creating a deployment bundle as a .tar.gz archive, instead of the .zip

The reasoning behind is this bug with the CodeDeploy tool, where someone reported it works without the memory leak if tgz is used, and apparently it works faster: https://github.com/aws/aws-codedeploy-agent/issues/32#issuecomment-538618262

I'm referring to this block in this utility: https://github.com/techpivot/aws-code-deploy/blob/4f671aad5ff3979a5546805a68d10d972112da9f/bin/aws-code-deploy.sh#L339-L357 - if it could support an option parameter to try the tar-gzipping, I'd like to try it out to see if that works better than gzip for the memory leak AWS doesn't really seem to put enough resources into really fixing it. 

Thanks

**Comment by virgofx** [comment]
Yeah we could easily do that.. as code deploy supports it. If you want to submit a PR feel free. Otherwise, I will try to test an update very soon
