### ISSUE TITLE
Inclusion of node-modules in zip / tar can trigger CodeDeploy memory leak

### ISSUE THREAD

**Issue by DuncanChud** [techpivot/aws-code-deploy#13]
Given that CodeDeploy has a memory leak based on the size of the zip it tries to extract  ( https://github.com/aws/aws-codedeploy-agent/issues/32 )  would be good if the zip / tar process excluded the node-modules itself, or an array of supplied directories.  If using the NPM version of the install its impossible to not have that be part of the archive itself currently. 

 I could do a PR for this if seems useful.

**Comment by KiamarzFallahi** [comment]
@DuncanChud I know the issue was opened a long time ago, but CodeDeploy is close to releasing a fix for the memory leak. Can you think of another use for the issue above in a world where the memory leak is resolved?

**Comment by virgofx** [comment]
Just getting around to this now. I believe this is somewhat custom. While we could do this in our script ... it makes more sent to *package* your directory for deployment as needed just prior to running this script during *deploy*. Meaning, if your application doesn't need `node_modules` or `vendor` make sure you appropriately build and package your distribution directory accordingly.

Then, everything inside `AWS_CODE_DEPLOY_APP_SOURCE` you have full control over as needed for your application.
