### ISSUE TITLE
Syntax issue on CircleCI

### ISSUE THREAD

**Issue by loicf69100** [techpivot/aws-code-deploy#3]
I use the following command on CircleCI:
- run:
          name: Deploy to S3
          command: sh /var/www/html/aws-code-deploy.sh

Then I got the following output from CircleCI:
#!/bin/bash -eo pipefail
sh /var/www/html/aws-code-deploy.sh

/var/www/html/aws-code-deploy.sh: 106: /var/www/html/aws-code-deploy.sh: Syntax error: "(" unexpected (expecting "}")
Exited with code 2

Any idea how I can solve that?

Please let me know if I can supply more information to solve the issue.

Thanks

**Comment by virgofx** [comment]
How are you including the file? Are you including it manually, NPM, composer?

Can you try updating the command to:

```
command: /var/www/html/aws-code-deploy.sh
```

**Comment by gregorskii** [comment]
Run it with bash not sh

**Comment by virgofx** [comment]
Thanks @gregorskii
