### ISSUE TITLE
I am trying to deploy the application with this script from circle CI. 

### ISSUE THREAD

**Issue by adnanmayo** [techpivot/aws-code-deploy#9]
![image](https://user-images.githubusercontent.com/9306690/54275910-b3d12e00-45ad-11e9-8654-51eb0215ea4c.png)

It is failing after this...What could be the possible reason?

**Comment by virgofx** [comment]
Do you have the full log in the CLI? what happens next?

If it's stalling in the in-progress --- next step could be to potentially check the AWS code deploy logs.
